# Data Preprocessing Template

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(X[:,1:]) #fit tinh toan tham so can thiet 
# X[:, 1:] = imputer.transform(X[:,1:])
X[:,1:] = imputer.fit_transform(X[:,1:])

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

[0] - index cua columns muon transform

passthrough - keep columns khong apply encoding

In [8]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the dependent variable

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)
print(type(y))

[0 1 0 0 1 1 0 1 0 1]
<class 'numpy.ndarray'>


## Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = None)

In [12]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]]


- ko apply feature scaling truoc khi split vi mean / median cua test set cung dc tinh trong khi training

# Feature scaling (k thuong dung cho nhung thuat toan co he so cho feature nhu regression)

standardisation (-3,3): work all time
normalisation (0,1): for some feature flow normal distribution

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

khong apply standard scale cho dummy variable

In [14]:
print(X_train)

[[0.0 0.0 1.0 -0.23314138480284194 -1.2010260813926417]
 [1.0 0.0 0.0 0.5426210991428982 0.5494572761027069]
 [1.0 0.0 0.0 1.1368221506758058 1.162126451226079]
 [0.0 1.0 0.0 1.4339226764422595 1.5122231227251486]
 [0.0 0.0 1.0 -1.9827333698719587 -1.5511227528917113]
 [1.0 0.0 0.0 -0.49723074103968984 0.11183643672886977]
 [0.0 1.0 0.0 -0.05157995239000921 -0.17018588197871387]
 [0.0 0.0 1.0 -0.34868047815646297 -0.4133085705197348]]


In [15]:
print(X_test)

[[1.0 0.0 0.0 -0.7943312668061436 -0.6758810741440371]
 [0.0 1.0 0.0 -1.537082581222278 -1.0259777456431067]]
